function dgdt = constantSpaceW(t,g,N,K,Da,x)

%dgdt = constantSpaceW(t,g,N,K,Da,x)
%Function produces vector of derivatives corresponding to wash phase MOL
%system. Wash phase version of (3.29).
%Uses constant spatial functions.

%Input:
%   t: vector of times generated by ode45
%   g: matrix of raw bound state concentration
%   N: Number of intervals (spatial) (yields N+1 points)
%   K: Reaction affinity constant
%   x: discretized linear space
%Output:
%   dgdt: vector of ODEs. Solving this yields bound state values.

%Last Modified: 6/17/14

alpha = Da/(3^(1/3)*gamma(2/3));

dgdt = zeros(N+1,1); %initialize.
dgdt(1) = -K*g(1); %first term - no integration.

%now build the rest of the vector
for i = 2:N+1
    sumval = dot(g(1:i-1),(x(i) - x(1:i-1)).^(1/3) - (x(i) - x(2:i)).^(1/3));
    dgdt(i) = -K*g(i) - (1 - g(i))*alpha*3*sumval;
end